### ISSUE TITLE
UCI protocol

### ISSUE THREAD

**Issue by AlexBrunetti** [LesterEvSe/AteNica#1]
Hello,
you call this an UCI engine, but it seems UCI protocol is not implemented. Could you please [check it](https://www.wbec-ridderkerk.nl/html/UCIProtocol.html), allowing using your engine in standard GUIs?

Thanks,
Alex

**Comment by LesterEvSe** [comment]
Okay, I'll work on that once I fix the bugs. At this stage, removed references to UCI in tags and README file
